import type { Question } from './types.js';

export const questions: Question[] = [
  // ── BOLLYWOOD ACTORS ──────────────────────────────────────────────────────
  {
    id: 'q1',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Indian_actor_Amitabh_Bachchan.jpg/500px-Indian_actor_Amitabh_Bachchan.jpg',
    answer: 'Amitabh Bachchan',
    aliases: ['amitabh', 'big b', 'amit ji', 'bacchhan', 'bachchan'],
    category: 'bollywood_actor',
    difficulty: 'easy',
    hint: 'Legendary actor known as the "Angry Young Man" of Bollywood',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q2',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6e/Shah_Rukh_Khan_graces_the_launch_of_the_new_Santro.jpg',
    answer: 'Shah Rukh Khan',
    aliases: ['srk', 'shahrukh', 'shahrukh khan', 'king khan', 'king of bollywood'],
    category: 'bollywood_actor',
    difficulty: 'easy',
    hint: 'Called the "King of Bollywood", known for romantic films',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q3',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Salman_Khan_in_2023_%281%29_%28cropped%29.jpg/500px-Salman_Khan_in_2023_(1)_(cropped).jpg',
    answer: 'Salman Khan',
    aliases: ['salman', 'bhai', 'bhaijaan', 'sultan'],
    category: 'bollywood_actor',
    difficulty: 'easy',
    hint: 'Known as "Bhai" to fans, famous for Dabangg and Tiger franchise',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q4',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/65/Aamir_Khan_at_the_success_bash_of_Secret_Superstar.jpg',
    answer: 'Aamir Khan',
    aliases: ['aamir', 'mr perfectionist', 'amir khan'],
    category: 'bollywood_actor',
    difficulty: 'easy',
    hint: 'Known as "Mr. Perfectionist", star of Dangal and 3 Idiots',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q5',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Deepika_Padukone_2025_%281%29.png/500px-Deepika_Padukone_2025_(1).png',
    answer: 'Deepika Padukone',
    aliases: ['deepika', 'dp', 'deeps'],
    category: 'bollywood_actor',
    difficulty: 'easy',
    hint: 'One of the highest-paid actresses in Bollywood',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q6',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/32/Ranveer_Singh_in_2023_%281%29_%28cropped%29.jpg',
    answer: 'Ranveer Singh',
    aliases: ['ranveer', 'ranvir'],
    category: 'bollywood_actor',
    difficulty: 'medium',
    hint: 'Known for energetic performances in Gully Boy and Bajirao Mastani',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q7',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/92/Hrithik_Roshan_in_2024_%28cropped%29.jpg',
    answer: 'Hrithik Roshan',
    aliases: ['hrithik', 'rithik', 'greek god of bollywood'],
    category: 'bollywood_actor',
    difficulty: 'easy',
    hint: 'Known as the "Greek God of Bollywood", star of Krrish and War',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q8',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Ranbir_Kapoor_snapped_at_Kalina_airport.jpg',
    answer: 'Ranbir Kapoor',
    aliases: ['ranbir', 'rk'],
    category: 'bollywood_actor',
    difficulty: 'medium',
    hint: 'Star of Brahmastra and Sanju, son of Rishi Kapoor',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q9',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/45/Priyanka_Chopra_at_Bulgary_launch%2C_2024_%28cropped%29.jpg',
    answer: 'Priyanka Chopra',
    aliases: ['priyanka', 'piggy chops', 'pc', 'priyanka chopra jonas'],
    category: 'bollywood_actor',
    difficulty: 'easy',
    hint: 'Miss World 2000, known for Krrish and international fame on Quantico',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q10',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Katrina_Kaif_at_the_Bharat_audio_launch.jpg/500px-Katrina_Kaif_at_the_Bharat_audio_launch.jpg',
    answer: 'Katrina Kaif',
    aliases: ['katrina', 'kat'],
    category: 'bollywood_actor',
    difficulty: 'medium',
    hint: 'Known for Tiger Zinda Hai and Phone Bhoot',
    submittedBy: 'FilmiGuess Team',
  },

  // ── HINDI MOVIES ──────────────────────────────────────────────────────────
  {
    id: 'q11',
    crop: { bottom: 56 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/8/80/Dilwale_Dulhania_Le_Jayenge_poster.jpg',
    answer: 'Dilwale Dulhania Le Jayenge',
    aliases: ['ddlj', 'dilwale dulhaniya', 'dilwale dulhania'],
    category: 'hindi_movie',
    difficulty: 'easy',
    hint: 'Longest-running Bollywood film in history, starring SRK and Kajol (1995)',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q12',
    crop: { bottom: 38 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/5/52/Sholay-poster.jpg',
    answer: 'Sholay',
    aliases: ['shola', 'sholaay'],
    category: 'classic_movie',
    difficulty: 'easy',
    hint: 'Classic 1975 film — "Kitne aadmi the?" Iconic Gabbar Singh dialogue',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q13',
    crop: { top: 30, bottom: 92 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/df/3_idiots_poster.jpg/500px-3_idiots_poster.jpg',
    answer: '3 Idiots',
    aliases: ['three idiots', 'tin idiots'],
    category: 'hindi_movie',
    difficulty: 'easy',
    hint: 'Aamir Khan comedy about engineering students — "All is well!"',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q14',
    crop: { top: 4, bottom: 63 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/99/Dangal_Poster.jpg/500px-Dangal_Poster.jpg',
    answer: 'Dangal',
    aliases: ['dangal movie'],
    category: 'hindi_movie',
    difficulty: 'easy',
    hint: 'Aamir Khan as wrestler Mahavir Singh Phogat, based on a true story',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q15',
    crop: { bottom: 44 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/c/cc/K.G.F_Chapter_1_poster.jpg',
    answer: 'KGF',
    aliases: ['kgf chapter 1', 'kolar gold fields', 'kgf 1'],
    category: 'hindi_movie',
    difficulty: 'medium',
    hint: 'Kannada blockbuster with Yash as Rocky, set in gold mines',
    submittedBy: 'FilmiGuess Team',
  },

  // ── SOUTH INDIAN ACTORS ───────────────────────────────────────────────────
  {
    id: 'q16',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Rajinikanth_in_2019.jpg/500px-Rajinikanth_in_2019.jpg',
    answer: 'Rajinikanth',
    aliases: ['rajini', 'thalaivar', 'superstar rajini', 'rajnikanth'],
    category: 'south_actor',
    difficulty: 'easy',
    hint: 'Tamil superstar known as "Thalaivar", iconic style with sunglasses',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q17',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Kamal_Haasan_at_2023_San_Diego_Comic-Con_International_by_Gage_Skidmore%2C_005_%28cropped%29.jpg/500px-Kamal_Haasan_at_2023_San_Diego_Comic-Con_International_by_Gage_Skidmore%2C_005_%28cropped%29.jpg',
    answer: 'Kamal Haasan',
    aliases: ['kamal', 'ulaganayagan'],
    category: 'south_actor',
    difficulty: 'medium',
    hint: 'Known as "Ulaganayagan", legendary Tamil actor and filmmaker',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q18',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/NTR_Jr._%282026%29.jpg/500px-NTR_Jr._(2026).jpg',
    answer: 'Jr NTR',
    aliases: ['jr ntr', 'junior ntr', 'ntr', 'tarak', 'young tiger'],
    category: 'south_actor',
    difficulty: 'medium',
    hint: 'Telugu star of RRR, grandson of NT Rama Rao',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q19',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Ram_Charan_at_Game_Changer_trailer_launch.jpg/500px-Ram_Charan_at_Game_Changer_trailer_launch.jpg',
    answer: 'Ram Charan',
    aliases: ['ramcharan', 'cherry', 'mega power star'],
    category: 'south_actor',
    difficulty: 'medium',
    hint: 'Telugu star of RRR and Magadheera, son of Chiranjeevi',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q20',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Allu_Arjun_at_Pushpa_2_The_Rule_meet.jpg/500px-Allu_Arjun_at_Pushpa_2_The_Rule_meet.jpg',
    answer: 'Allu Arjun',
    aliases: ['allu', 'bunny', 'stylish star', 'icon star'],
    category: 'south_actor',
    difficulty: 'easy',
    hint: '"Pushpa — I hate tears!" Star of the Pushpa franchise',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q21',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Prabhas_by_Gage_Skidmore.jpg/500px-Prabhas_by_Gage_Skidmore.jpg',
    answer: 'Prabhas',
    aliases: ['prabhas', 'darling', 'rebel star'],
    category: 'south_actor',
    difficulty: 'medium',
    hint: 'Star of Baahubali, first South Indian actor with pan-India fame',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q22',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/C._Joseph_Vijay_%28cropped%29.jpg/500px-C._Joseph_Vijay_(cropped).jpg',
    answer: 'Vijay',
    aliases: ['thalapathy vijay', 'thalapathy', 'joseph vijay'],
    category: 'south_actor',
    difficulty: 'easy',
    hint: 'Tamil superstar known as "Thalapathy", star of Leo and Varisu',
    submittedBy: 'FilmiGuess Team',
  },

  // ── CLASSIC MOVIES ────────────────────────────────────────────────────────
  {
    id: 'q23',
    crop: { top: 23, bottom: 80 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/16/Mughal-e-Azam.jpg/500px-Mughal-e-Azam.jpg',
    answer: 'Mughal-E-Azam',
    aliases: ['mughal e azam', 'mughal e alam', 'mughle azam'],
    category: 'classic_movie',
    difficulty: 'medium',
    hint: 'Epic 1960 historical film about Mughal Emperor Akbar and Anarkali',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q24',
    crop: { top: 53, bottom: 94 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c7/Deewaar_poster.jpg',
    answer: 'Deewar',
    aliases: ['deewar 1975', 'deewaar'],
    category: 'classic_movie',
    difficulty: 'medium',
    hint: '1975 Amitabh Bachchan film — "Mere paas maa hai"',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q25',
    crop: { bottom: 70 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/5/5f/Baahubali_The_Beginning_poster.jpg',
    answer: 'Baahubali',
    aliases: ['bahubali', 'baahubali the beginning', 'bahubali 1'],
    category: 'hindi_movie',
    difficulty: 'easy',
    hint: '"Why did Kattappa kill Baahubali?" — SS Rajamouli\'s epic with Prabhas',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q26',
    crop: { bottom: 60 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d7/RRR_Poster.jpg/500px-RRR_Poster.jpg',
    answer: 'RRR',
    aliases: ['rrr movie', 'rise roar revolt', 'roudram ranam rudhiram'],
    category: 'hindi_movie',
    difficulty: 'easy',
    hint: 'SS Rajamouli\'s film with Ram Charan and Jr NTR — "Naatu Naatu"',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q27',
    crop: { bottom: 64 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/4/4d/Kabhi_Khushi_Kabhie_Gham..._poster.jpg',
    answer: 'Kabhi Khushi Kabhie Gham',
    aliases: ['k3g', 'kabhi khushi kabhi gham', 'k 3 g'],
    category: 'hindi_movie',
    difficulty: 'medium',
    hint: '2001 Karan Johar family drama with SRK, Kajol, Hrithik — "It\'s all about loving your parents"',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q28',
    crop: { top: 26 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/1/17/Zindagi_Na_Milegi_Dobara.jpg',
    answer: 'Zindagi Na Milegi Dobara',
    aliases: ['znmd', 'zindagi na milegi dobara'],
    category: 'hindi_movie',
    difficulty: 'medium',
    hint: 'Zoya Akhtar\'s road trip film with Hrithik, Farhan, Abhay Deol — "You only live once"',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q29',
    crop: { bottom: 68 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b6/Lagaan.jpg',
    answer: 'Lagaan',
    aliases: ['lagaan 2001', 'once upon a time in india'],
    category: 'classic_movie',
    difficulty: 'medium',
    hint: 'Aamir Khan cricket film that was nominated for Oscar Best Foreign Film (2001)',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q30',
    crop: { top: 20, bottom: 72 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/d/db/Dil_Chahta_Hai.jpg',
    answer: 'Dil Chahta Hai',
    aliases: ['dil chahta he', 'dch'],
    category: 'hindi_movie',
    difficulty: 'medium',
    hint: 'Farhan Akhtar\'s 2001 buddy film with Aamir, Saif, Akshaye Khanna',
    submittedBy: 'FilmiGuess Team',
  },
];

export function getQuestionsByCategories(categories: string[], count: number): Question[] {
  const filtered = questions.filter(q =>
    categories.length === 0 || categories.includes(q.category)
  );
  const shuffled = [...filtered].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}
