import type { Question } from './types.js';

/**
 * Bundled question bank — used directly when Supabase isn't configured and as
 * the seed source for the `questions` table (see scripts/seed.ts).
 */
export const questionBank: Question[] = [
  // ── BOLLYWOOD ACTORS ──────────────────────────────────────────────────────
  {
    id: 'q1',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Indian_actor_Amitabh_Bachchan.jpg/500px-Indian_actor_Amitabh_Bachchan.jpg',
    answer: 'Amitabh Bachchan',
    aliases: ['amitabh', 'big b', 'amit ji', 'bacchhan', 'bachchan'],
    category: 'bollywood_actor',
    difficulty: 'easy',
    hint: 'Legendary actor known as the "Angry Young Man" of Bollywood',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q2',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6e/Shah_Rukh_Khan_graces_the_launch_of_the_new_Santro.jpg',
    answer: 'Shah Rukh Khan',
    aliases: ['srk', 'shahrukh', 'shahrukh khan', 'king khan', 'king of bollywood'],
    category: 'bollywood_actor',
    difficulty: 'easy',
    hint: 'Called the "King of Bollywood", known for romantic films',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q3',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Salman_Khan_in_2023_%281%29_%28cropped%29.jpg/500px-Salman_Khan_in_2023_(1)_(cropped).jpg',
    answer: 'Salman Khan',
    aliases: ['salman', 'bhai', 'bhaijaan', 'sultan'],
    category: 'bollywood_actor',
    difficulty: 'easy',
    hint: 'Known as "Bhai" to fans, famous for Dabangg and Tiger franchise',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q4',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/65/Aamir_Khan_at_the_success_bash_of_Secret_Superstar.jpg',
    answer: 'Aamir Khan',
    aliases: ['aamir', 'mr perfectionist', 'amir khan'],
    category: 'bollywood_actor',
    difficulty: 'easy',
    hint: 'Known as "Mr. Perfectionist", star of Dangal and 3 Idiots',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q5',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Deepika_Padukone_2025_%281%29.png/500px-Deepika_Padukone_2025_(1).png',
    answer: 'Deepika Padukone',
    aliases: ['deepika', 'dp', 'deeps'],
    category: 'bollywood_actor',
    difficulty: 'easy',
    hint: 'One of the highest-paid actresses in Bollywood',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q6',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/32/Ranveer_Singh_in_2023_%281%29_%28cropped%29.jpg',
    answer: 'Ranveer Singh',
    aliases: ['ranveer', 'ranvir'],
    category: 'bollywood_actor',
    difficulty: 'medium',
    hint: 'Known for energetic performances in Gully Boy and Bajirao Mastani',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q7',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/9/92/Hrithik_Roshan_in_2024_%28cropped%29.jpg',
    answer: 'Hrithik Roshan',
    aliases: ['hrithik', 'rithik', 'greek god of bollywood'],
    category: 'bollywood_actor',
    difficulty: 'easy',
    hint: 'Known as the "Greek God of Bollywood", star of Krrish and War',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q8',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a0/Ranbir_Kapoor_snapped_at_Kalina_airport.jpg',
    answer: 'Ranbir Kapoor',
    aliases: ['ranbir', 'rk'],
    category: 'bollywood_actor',
    difficulty: 'medium',
    hint: 'Star of Brahmastra and Sanju, son of Rishi Kapoor',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q9',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/45/Priyanka_Chopra_at_Bulgary_launch%2C_2024_%28cropped%29.jpg',
    answer: 'Priyanka Chopra',
    aliases: ['priyanka', 'piggy chops', 'pc', 'priyanka chopra jonas'],
    category: 'bollywood_actor',
    difficulty: 'easy',
    hint: 'Miss World 2000, known for Krrish and international fame on Quantico',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q10',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Katrina_Kaif_at_the_Bharat_audio_launch.jpg/500px-Katrina_Kaif_at_the_Bharat_audio_launch.jpg',
    answer: 'Katrina Kaif',
    aliases: ['katrina', 'kat'],
    category: 'bollywood_actor',
    difficulty: 'medium',
    hint: 'Known for Tiger Zinda Hai and Phone Bhoot',
    submittedBy: 'FilmiGuess Team',
  },

  // ── HINDI MOVIES ──────────────────────────────────────────────────────────
  {
    id: 'q11',
    crop: { bottom: 56 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/8/80/Dilwale_Dulhania_Le_Jayenge_poster.jpg',
    answer: 'Dilwale Dulhania Le Jayenge',
    aliases: ['ddlj', 'dilwale dulhaniya', 'dilwale dulhania'],
    category: 'hindi_movie',
    difficulty: 'easy',
    hint: 'Longest-running Bollywood film in history, starring SRK and Kajol (1995)',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q12',
    crop: { bottom: 38 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/5/52/Sholay-poster.jpg',
    answer: 'Sholay',
    aliases: ['shola', 'sholaay'],
    category: 'classic_movie',
    difficulty: 'easy',
    hint: 'Classic 1975 film — "Kitne aadmi the?" Iconic Gabbar Singh dialogue',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q13',
    crop: { top: 30, bottom: 92 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/df/3_idiots_poster.jpg/500px-3_idiots_poster.jpg',
    answer: '3 Idiots',
    aliases: ['three idiots', 'tin idiots'],
    category: 'hindi_movie',
    difficulty: 'easy',
    hint: 'Aamir Khan comedy about engineering students — "All is well!"',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q14',
    crop: { top: 4, bottom: 63 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/9/99/Dangal_Poster.jpg/500px-Dangal_Poster.jpg',
    answer: 'Dangal',
    aliases: ['dangal movie'],
    category: 'hindi_movie',
    difficulty: 'easy',
    hint: 'Aamir Khan as wrestler Mahavir Singh Phogat, based on a true story',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q15',
    crop: { bottom: 44 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/c/cc/K.G.F_Chapter_1_poster.jpg',
    answer: 'KGF',
    aliases: ['kgf chapter 1', 'kolar gold fields', 'kgf 1'],
    category: 'hindi_movie',
    difficulty: 'medium',
    hint: 'Kannada blockbuster with Yash as Rocky, set in gold mines',
    submittedBy: 'FilmiGuess Team',
  },

  // ── SOUTH INDIAN ACTORS ───────────────────────────────────────────────────
  {
    id: 'q16',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d2/Rajinikanth_in_2019.jpg/500px-Rajinikanth_in_2019.jpg',
    answer: 'Rajinikanth',
    aliases: ['rajini', 'thalaivar', 'superstar rajini', 'rajnikanth'],
    category: 'south_actor',
    difficulty: 'easy',
    hint: 'Tamil superstar known as "Thalaivar", iconic style with sunglasses',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q17',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Kamal_Haasan_at_2023_San_Diego_Comic-Con_International_by_Gage_Skidmore%2C_005_%28cropped%29.jpg/500px-Kamal_Haasan_at_2023_San_Diego_Comic-Con_International_by_Gage_Skidmore%2C_005_%28cropped%29.jpg',
    answer: 'Kamal Haasan',
    aliases: ['kamal', 'ulaganayagan'],
    category: 'south_actor',
    difficulty: 'medium',
    hint: 'Known as "Ulaganayagan", legendary Tamil actor and filmmaker',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q18',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/NTR_Jr._%282026%29.jpg/500px-NTR_Jr._(2026).jpg',
    answer: 'Jr NTR',
    aliases: ['jr ntr', 'junior ntr', 'ntr', 'tarak', 'young tiger'],
    category: 'south_actor',
    difficulty: 'medium',
    hint: 'Telugu star of RRR, grandson of NT Rama Rao',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q19',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Ram_Charan_at_Game_Changer_trailer_launch.jpg/500px-Ram_Charan_at_Game_Changer_trailer_launch.jpg',
    answer: 'Ram Charan',
    aliases: ['ramcharan', 'cherry', 'mega power star'],
    category: 'south_actor',
    difficulty: 'medium',
    hint: 'Telugu star of RRR and Magadheera, son of Chiranjeevi',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q20',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Allu_Arjun_at_Pushpa_2_The_Rule_meet.jpg/500px-Allu_Arjun_at_Pushpa_2_The_Rule_meet.jpg',
    answer: 'Allu Arjun',
    aliases: ['allu', 'bunny', 'stylish star', 'icon star'],
    category: 'south_actor',
    difficulty: 'easy',
    hint: '"Pushpa — I hate tears!" Star of the Pushpa franchise',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q21',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Prabhas_by_Gage_Skidmore.jpg/500px-Prabhas_by_Gage_Skidmore.jpg',
    answer: 'Prabhas',
    aliases: ['prabhas', 'darling', 'rebel star'],
    category: 'south_actor',
    difficulty: 'medium',
    hint: 'Star of Baahubali, first South Indian actor with pan-India fame',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q22',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/C._Joseph_Vijay_%28cropped%29.jpg/500px-C._Joseph_Vijay_(cropped).jpg',
    answer: 'Vijay',
    aliases: ['thalapathy vijay', 'thalapathy', 'joseph vijay'],
    category: 'south_actor',
    difficulty: 'easy',
    hint: 'Tamil superstar known as "Thalapathy", star of Leo and Varisu',
    submittedBy: 'FilmiGuess Team',
  },

  // ── CLASSIC MOVIES ────────────────────────────────────────────────────────
  {
    id: 'q23',
    crop: { top: 23, bottom: 80 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/1/16/Mughal-e-Azam.jpg/500px-Mughal-e-Azam.jpg',
    answer: 'Mughal-E-Azam',
    aliases: ['mughal e azam', 'mughal e alam', 'mughle azam'],
    category: 'classic_movie',
    difficulty: 'medium',
    hint: 'Epic 1960 historical film about Mughal Emperor Akbar and Anarkali',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q24',
    crop: { top: 53, bottom: 94 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c7/Deewaar_poster.jpg',
    answer: 'Deewar',
    aliases: ['deewar 1975', 'deewaar'],
    category: 'classic_movie',
    difficulty: 'medium',
    hint: '1975 Amitabh Bachchan film — "Mere paas maa hai"',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q25',
    crop: { bottom: 70 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/5/5f/Baahubali_The_Beginning_poster.jpg',
    answer: 'Baahubali',
    aliases: ['bahubali', 'baahubali the beginning', 'bahubali 1'],
    category: 'hindi_movie',
    difficulty: 'easy',
    hint: '"Why did Kattappa kill Baahubali?" — SS Rajamouli\'s epic with Prabhas',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q26',
    crop: { bottom: 60 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d7/RRR_Poster.jpg/500px-RRR_Poster.jpg',
    answer: 'RRR',
    aliases: ['rrr movie', 'rise roar revolt', 'roudram ranam rudhiram'],
    category: 'hindi_movie',
    difficulty: 'easy',
    hint: 'SS Rajamouli\'s film with Ram Charan and Jr NTR — "Naatu Naatu"',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q27',
    crop: { bottom: 64 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/4/4d/Kabhi_Khushi_Kabhie_Gham..._poster.jpg',
    answer: 'Kabhi Khushi Kabhie Gham',
    aliases: ['k3g', 'kabhi khushi kabhi gham', 'k 3 g'],
    category: 'hindi_movie',
    difficulty: 'medium',
    hint: '2001 Karan Johar family drama with SRK, Kajol, Hrithik — "It\'s all about loving your parents"',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q28',
    crop: { top: 26 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/1/17/Zindagi_Na_Milegi_Dobara.jpg',
    answer: 'Zindagi Na Milegi Dobara',
    aliases: ['znmd', 'zindagi na milegi dobara'],
    category: 'hindi_movie',
    difficulty: 'medium',
    hint: 'Zoya Akhtar\'s road trip film with Hrithik, Farhan, Abhay Deol — "You only live once"',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q29',
    crop: { bottom: 68 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b6/Lagaan.jpg',
    answer: 'Lagaan',
    aliases: ['lagaan 2001', 'once upon a time in india'],
    category: 'classic_movie',
    difficulty: 'medium',
    hint: 'Aamir Khan cricket film that was nominated for Oscar Best Foreign Film (2001)',
    submittedBy: 'FilmiGuess Team',
  },
  {
    id: 'q30',
    crop: { top: 20, bottom: 72 },  // cut the printed title out of the poster
    imageUrl: 'https://upload.wikimedia.org/wikipedia/en/d/db/Dil_Chahta_Hai.jpg',
    answer: 'Dil Chahta Hai',
    aliases: ['dil chahta he', 'dch'],
    category: 'hindi_movie',
    difficulty: 'medium',
    hint: 'Farhan Akhtar\'s 2001 buddy film with Aamir, Saif, Akshaye Khanna',
    submittedBy: 'FilmiGuess Team',
  },

  {"id":"q31","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Akshay_Kumar_National_Award_for_Padman_%28cropped%29.jpg/500px-Akshay_Kumar_National_Award_for_Padman_%28cropped%29.jpg","answer":"Akshay Kumar","aliases":["akshay","akki","khiladi"],"category":"bollywood_actor","difficulty":"easy","hint":"The \"Khiladi\" of Bollywood — action, comedy and 4am discipline","submittedBy":"FilmiGuess Team"},
  {"id":"q32","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/9/9d/Ajay_Devgn_at_the_trailer_launch_of_Raid_2.jpg","answer":"Ajay Devgn","aliases":["ajay devgan","singham"],"category":"bollywood_actor","difficulty":"easy","hint":"Singham himself — intense eyes, Drishyam and Tanhaji","submittedBy":"FilmiGuess Team"},
  {"id":"q33","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/25/Shahid_Kapoor_at_Bloody_Daddy_launch_%28cropped%29.jpg/500px-Shahid_Kapoor_at_Bloody_Daddy_launch_%28cropped%29.jpg","answer":"Shahid Kapoor","aliases":["shahid"],"category":"bollywood_actor","difficulty":"medium","hint":"Kabir Singh and Jab We Met star","submittedBy":"FilmiGuess Team"},
  {"id":"q34","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Varun_Dhawan_at_Mehboob_Studios_in_2025_%28cropped%29.jpg/500px-Varun_Dhawan_at_Mehboob_Studios_in_2025_%28cropped%29.jpg","answer":"Varun Dhawan","aliases":["varun"],"category":"bollywood_actor","difficulty":"medium","hint":"Student of the Year debutant, son of director David Dhawan","submittedBy":"FilmiGuess Team"},
  {"id":"q35","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Alia_Bhatt_attends_at_the_2026_Cannes_Film_Festival_%28cropped%29_%28cropped%29.jpg/500px-Alia_Bhatt_attends_at_the_2026_Cannes_Film_Festival_%28cropped%29_%28cropped%29.jpg","answer":"Alia Bhatt","aliases":["alia","aalia"],"category":"bollywood_actor","difficulty":"easy","hint":"Gangubai Kathiawadi and Raazi star","submittedBy":"FilmiGuess Team"},
  {"id":"q36","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/2/29/Kareena_Kapoor_Khan_in_2023_%281%29_%28cropped%29.jpg","answer":"Kareena Kapoor","aliases":["kareena","bebo","kareena kapoor khan"],"category":"bollywood_actor","difficulty":"easy","hint":"\"Poo\" from K3G, Geet from Jab We Met","submittedBy":"FilmiGuess Team"},
  {"id":"q37","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/4/41/Kajol_snapped_promoting_Maa_%28cropped%29.jpg","answer":"Kajol","aliases":["kajol devgan"],"category":"bollywood_actor","difficulty":"easy","hint":"Simran of DDLJ, Anjali of Kuch Kuch Hota Hai","submittedBy":"FilmiGuess Team"},
  {"id":"q38","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Madhuri_Dixit_in_November_2022.jpg/500px-Madhuri_Dixit_in_November_2022.jpg","answer":"Madhuri Dixit","aliases":["madhuri","dhak dhak girl"],"category":"bollywood_actor","difficulty":"easy","hint":"The \"Dhak Dhak\" girl — dancing legend of the 90s","submittedBy":"FilmiGuess Team"},
  {"id":"q39","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Sridevi.jpg/500px-Sridevi.jpg","answer":"Sridevi","aliases":["sri devi"],"category":"bollywood_actor","difficulty":"medium","hint":"India’s first female superstar — Chandni and Mr. India","submittedBy":"FilmiGuess Team"},
  {"id":"q40","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/a/a2/Rekha_2023.jpg","answer":"Rekha","aliases":["rekha ji"],"category":"bollywood_actor","difficulty":"medium","hint":"Umrao Jaan herself — the evergreen diva","submittedBy":"FilmiGuess Team"},
  {"id":"q41","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/e/e6/Anushka_Sharma_promoting_Zero.jpg","answer":"Anushka Sharma","aliases":["anushka"],"category":"bollywood_actor","difficulty":"easy","hint":"PK and Band Baaja Baaraat star, married to Virat Kohli","submittedBy":"FilmiGuess Team"},
  {"id":"q42","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Actor_Rajkummar_Rao.jpg/3840px-Actor_Rajkummar_Rao.jpg","answer":"Rajkummar Rao","aliases":["rajkumar rao","rajkummar"],"category":"bollywood_actor","difficulty":"medium","hint":"Stree and Newton star","submittedBy":"FilmiGuess Team"},
  {"id":"q43","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/e/e4/Ayushmann_Khurrana_promotos_%27Anek%27_in_Delhi_%281%29_%28cropped%29.jpg","answer":"Ayushmann Khurrana","aliases":["ayushman","ayushmann"],"category":"bollywood_actor","difficulty":"medium","hint":"Vicky Donor and Andhadhun star","submittedBy":"FilmiGuess Team"},
  {"id":"q44","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/b/b1/Kartik_Aaryan_in_2025_at_23rd_Zee_Cine_Awards_2025.jpg","answer":"Kartik Aaryan","aliases":["kartik","kartik aryan"],"category":"bollywood_actor","difficulty":"medium","hint":"Bhool Bhulaiyaa 2 and Pyaar Ka Punchnama star","submittedBy":"FilmiGuess Team"},
  {"id":"q45","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/1/14/Vicky_Kaushal_snapped_promoting_Zara_Hatke_Zara_Bach_Ke_on_the_sets_of_The_Kapil_Sharma_Show_%28cropped%29.jpg","answer":"Vicky Kaushal","aliases":["vicky"],"category":"bollywood_actor","difficulty":"medium","hint":"Uri’s Major Vihaan — \"How’s the josh?\"","submittedBy":"FilmiGuess Team"},
  {"id":"q46","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Nawazuddin_Siddiqui_at_IFFK_2021_4_%28cropped%29.jpg/1920px-Nawazuddin_Siddiqui_at_IFFK_2021_4_%28cropped%29.jpg","answer":"Nawazuddin Siddiqui","aliases":["nawaz","nawazuddin"],"category":"bollywood_actor","difficulty":"hard","hint":"Gangs of Wasseypur’s Faizal Khan","submittedBy":"FilmiGuess Team"},
  {"id":"q47","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Pankaj_Tripathi_World_Premiere_Newton_Zoopalast_Berlinale_2017_06.jpg/500px-Pankaj_Tripathi_World_Premiere_Newton_Zoopalast_Berlinale_2017_06.jpg","answer":"Pankaj Tripathi","aliases":["pankaj"],"category":"bollywood_actor","difficulty":"hard","hint":"Mirzapur’s Kaleen Bhaiya — quiet scene-stealer","submittedBy":"FilmiGuess Team"},
  {"id":"q48","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Irrfan_Khan_Profile.jpg/500px-Irrfan_Khan_Profile.jpg","answer":"Irrfan Khan","aliases":["irfan khan","irrfan"],"category":"bollywood_actor","difficulty":"medium","hint":"The Lunchbox and Piku — India’s acting export to Hollywood","submittedBy":"FilmiGuess Team"},
  {"id":"q49","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/33/Sanjay_dutt_department.jpg/500px-Sanjay_dutt_department.jpg","answer":"Sanjay Dutt","aliases":["sanju","munna bhai","sanjay"],"category":"bollywood_actor","difficulty":"easy","hint":"Munna Bhai himself","submittedBy":"FilmiGuess Team"},
  {"id":"q50","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/0/08/Anil_Kapoor_1.jpeg","answer":"Anil Kapoor","aliases":["anil","lakhan"],"category":"bollywood_actor","difficulty":"easy","hint":"Mr. India — jhakaas!","submittedBy":"FilmiGuess Team"},
  {"id":"q51","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Govind_dev_ji.jpg/500px-Govind_dev_ji.jpg","answer":"Govinda","aliases":["chichi","govinda ahuja"],"category":"bollywood_actor","difficulty":"medium","hint":"Hero No. 1 — the 90s comedy king","submittedBy":"FilmiGuess Team"},
  {"id":"q52","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Tabu_in_2024.jpg/500px-Tabu_in_2024.jpg","answer":"Tabu","aliases":["tabassum"],"category":"bollywood_actor","difficulty":"hard","hint":"Andhadhun and Haider’s acclaimed actress","submittedBy":"FilmiGuess Team"},
  {"id":"q53","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/e/e4/Vidya_Balan_at_BB3_interviews%2C_2024_%28cropped%29.jpg","answer":"Vidya Balan","aliases":["vidya"],"category":"bollywood_actor","difficulty":"medium","hint":"Kahaani and The Dirty Picture star","submittedBy":"FilmiGuess Team"},
  {"id":"q54","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/8/8b/Saif_SG_screening.jpg","answer":"Saif Ali Khan","aliases":["saif","nawab"],"category":"bollywood_actor","difficulty":"easy","hint":"The Nawab of Bollywood — Omkara, Sacred Games","submittedBy":"FilmiGuess Team"},
  {"id":"q55","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/7/76/Rani_Mukerji_snapped_at_Hema_Malini%E2%80%99s_75th_birthday_celebration_%28cropped%29%282%29.jpg","answer":"Rani Mukerji","aliases":["rani mukherjee","rani"],"category":"bollywood_actor","difficulty":"medium","hint":"Tina of Kuch Kuch Hota Hai, the Mardaani cop","submittedBy":"FilmiGuess Team"},
  {"id":"q56","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Preity_Zinta_by_Ash_Gupta.jpg/500px-Preity_Zinta_by_Ash_Gupta.jpg","answer":"Preity Zinta","aliases":["preity","priety zinta"],"category":"bollywood_actor","difficulty":"medium","hint":"The dimpled star of Kal Ho Naa Ho and Veer-Zaara","submittedBy":"FilmiGuess Team"},
  {"id":"q57","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/b/b3/Tiger_Shroff_in_2019.jpg","answer":"Tiger Shroff","aliases":["tiger"],"category":"bollywood_actor","difficulty":"easy","hint":"Baaghi action star, son of Jackie Shroff","submittedBy":"FilmiGuess Team"},
  {"id":"q58","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/e/e0/JohnAbraham.jpg","answer":"John Abraham","aliases":["john"],"category":"bollywood_actor","difficulty":"medium","hint":"Dhoom’s biker villain, Pathaan’s antagonist","submittedBy":"FilmiGuess Team"},
  {"id":"q59","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Kiara_Advani_snapped_at_the_screening_of_Shershaah_%28cropped%29.jpg/500px-Kiara_Advani_snapped_at_the_screening_of_Shershaah_%28cropped%29.jpg","answer":"Kiara Advani","aliases":["kiara"],"category":"bollywood_actor","difficulty":"easy","hint":"Kabir Singh and Shershaah star","submittedBy":"FilmiGuess Team"},
  {"id":"q60","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/9/9b/Sara_Ali_Khan_snapped_promoting_Zara_Hatke_Zara_Bach_Ke_on_the_sets_of_The_Kapil_Sharma_Show_%288%29_%28cropped%29.jpg","answer":"Sara Ali Khan","aliases":["sara"],"category":"bollywood_actor","difficulty":"medium","hint":"Kedarnath debutante, Saif’s daughter","submittedBy":"FilmiGuess Team"},
  {"id":"q61","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Mahesh_Babu_in_Spyder_%28cropped%29.jpg/500px-Mahesh_Babu_in_Spyder_%28cropped%29.jpg","answer":"Mahesh Babu","aliases":["mahesh","prince"],"category":"south_actor","difficulty":"easy","hint":"Telugu cinema’s \"Prince\" — Pokiri and Srimanthudu","submittedBy":"FilmiGuess Team"},
  {"id":"q62","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Chiranjeevi_at_ANR_Awards_2024_%28cropped%29.jpg/500px-Chiranjeevi_at_ANR_Awards_2024_%28cropped%29.jpg","answer":"Chiranjeevi","aliases":["megastar","chiru"],"category":"south_actor","difficulty":"medium","hint":"The Megastar of Telugu cinema, Ram Charan’s father","submittedBy":"FilmiGuess Team"},
  {"id":"q63","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Shri_Konidela_Pawan_Kalyan.jpg/500px-Shri_Konidela_Pawan_Kalyan.jpg","answer":"Pawan Kalyan","aliases":["power star","pspk"],"category":"south_actor","difficulty":"medium","hint":"Telugu’s \"Power Star\" turned politician","submittedBy":"FilmiGuess Team"},
  {"id":"q64","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Nagarjuna_Akkineni_at_ANR_Awards.jpg/500px-Nagarjuna_Akkineni_at_ANR_Awards.jpg","answer":"Nagarjuna","aliases":["nag","akkineni nagarjuna"],"category":"south_actor","difficulty":"medium","hint":"The Akkineni \"King\" — Shiva and Manam","submittedBy":"FilmiGuess Team"},
  {"id":"q65","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Retro_audio_launch_-_Suriya.jpg/500px-Retro_audio_launch_-_Suriya.jpg","answer":"Suriya","aliases":["surya"],"category":"south_actor","difficulty":"medium","hint":"Soorarai Pottru and Singam star","submittedBy":"FilmiGuess Team"},
  {"id":"q66","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Dhanush_at_the_%E2%80%98Asuran%E2%80%99_Success_Meet_%28cropped%29.jpg/500px-Dhanush_at_the_%E2%80%98Asuran%E2%80%99_Success_Meet_%28cropped%29.jpg","answer":"Dhanush","aliases":["dhanush k raja"],"category":"south_actor","difficulty":"easy","hint":"The \"Why This Kolaveri Di\" singer-actor","submittedBy":"FilmiGuess Team"},
  {"id":"q67","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Ajith_Kumar_at_Irungattukottai_Race_Track.jpg/500px-Ajith_Kumar_at_Irungattukottai_Race_Track.jpg","answer":"Ajith Kumar","aliases":["ajith","thala","ak"],"category":"south_actor","difficulty":"medium","hint":"\"Thala\" of Tamil cinema — Mankatha, Valimai","submittedBy":"FilmiGuess Team"},
  {"id":"q68","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/0/0c/Yash%2C_Vishal%2C_Srinidhi_Shetty_at_the_%E2%80%98KGF%E2%80%99_Press_Meet_In_Chennai_%28cropped%29.jpg","answer":"Yash","aliases":["rocking star","naveen kumar gowda"],"category":"south_actor","difficulty":"easy","hint":"KGF’s Rocky bhai — the Rocking Star","submittedBy":"FilmiGuess Team"},
  {"id":"q69","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/c/c9/Mohanlal_%28cropped%29.jpg/500px-Mohanlal_%28cropped%29.jpg","answer":"Mohanlal","aliases":["lalettan"],"category":"south_actor","difficulty":"medium","hint":"Malayalam’s complete actor — the original Drishyam","submittedBy":"FilmiGuess Team"},
  {"id":"q70","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Mammootty%2C_2022.jpg/500px-Mammootty%2C_2022.jpg","answer":"Mammootty","aliases":["mammooty","mammukka"],"category":"south_actor","difficulty":"hard","hint":"Malayalam megastar with three National Awards","submittedBy":"FilmiGuess Team"},
  {"id":"q71","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/8/82/Dulquer_Salmaan_at_Karwaan_promotions_%28cropped%29.jpg","answer":"Dulquer Salmaan","aliases":["dq","dulquer"],"category":"south_actor","difficulty":"medium","hint":"Malayalam heartthrob — OK Kanmani and Sita Ramam","submittedBy":"FilmiGuess Team"},
  {"id":"q72","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Fahadh_Faasil_2019.jpg/500px-Fahadh_Faasil_2019.jpg","answer":"Fahadh Faasil","aliases":["fafa","fahad fazil"],"category":"south_actor","difficulty":"hard","hint":"Pushpa’s Bhanwar Singh Shekhawat — Malayalam’s finest","submittedBy":"FilmiGuess Team"},
  {"id":"q73","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/8/80/Nayanthara_at_Filmfare_Awards.jpg","answer":"Nayanthara","aliases":["lady superstar"],"category":"south_actor","difficulty":"easy","hint":"The \"Lady Superstar\" of Tamil cinema","submittedBy":"FilmiGuess Team"},
  {"id":"q74","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Samantha_at_Kushi_Musical_concert_%282%29_%28cropped%29.jpg/500px-Samantha_at_Kushi_Musical_concert_%282%29_%28cropped%29.jpg","answer":"Samantha","aliases":["samantha ruth prabhu","sam"],"category":"south_actor","difficulty":"easy","hint":"\"Oo Antava\" — The Family Man season 2","submittedBy":"FilmiGuess Team"},
  {"id":"q75","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/4/4b/Rashmika-Mandanna_at_the_music_launch_of_Chhaava_%28cropped%29.jpg","answer":"Rashmika Mandanna","aliases":["rashmika"],"category":"south_actor","difficulty":"easy","hint":"Srivalli of Pushpa — the \"National Crush\"","submittedBy":"FilmiGuess Team"},
  {"id":"q76","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Vijay_Deverakonda_at_NOTA_pressmeet_2_%28cropped%29.jpg/500px-Vijay_Deverakonda_at_NOTA_pressmeet_2_%28cropped%29.jpg","answer":"Vijay Deverakonda","aliases":["vd","deverakonda"],"category":"south_actor","difficulty":"easy","hint":"Arjun Reddy himself — the original \"rowdy\"","submittedBy":"FilmiGuess Team"},
  {"id":"q77","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/b/b9/Anushka_at_the_trailer_launch_of_Baahubali_%28cropped%29.jpg","answer":"Anushka Shetty","aliases":["sweety"],"category":"south_actor","difficulty":"medium","hint":"Devasena of Baahubali","submittedBy":"FilmiGuess Team"},
  {"id":"q78","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/4/4b/Tamil-Actor-Vikram-Looking-Very-Smart-And-Stylish-Photos-20.jpg","answer":"Vikram","aliases":["chiyaan","chiyaan vikram"],"category":"south_actor","difficulty":"hard","hint":"\"Chiyaan\" — Anniyan and Ponniyin Selvan","submittedBy":"FilmiGuess Team"},
  {"id":"q79","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Keerthy_Suresh_at_Bhola_Shankar_pre_release_event_%282%29_%28cropped%29.jpg/500px-Keerthy_Suresh_at_Bhola_Shankar_pre_release_event_%282%29_%28cropped%29.jpg","answer":"Keerthy Suresh","aliases":["keerthi suresh"],"category":"south_actor","difficulty":"hard","hint":"Mahanati’s National Award-winning Savitri","submittedBy":"FilmiGuess Team"},
  {"id":"q80","imageUrl":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Trisha_Krishnan_at_PS1_pre_release_event_%283%29_%28cropped%29.jpg/500px-Trisha_Krishnan_at_PS1_pre_release_event_%283%29_%28cropped%29.jpg","answer":"Trisha","aliases":["trisha krishnan"],"category":"south_actor","difficulty":"medium","hint":"Ponniyin Selvan’s Kundavai — Tamil cinema’s queen","submittedBy":"FilmiGuess Team"},
  {"id":"q81","imageUrl":"https://upload.wikimedia.org/wikipedia/en/c/c3/PK_poster.jpg","answer":"PK","aliases":["pk movie","peekay"],"category":"hindi_movie","difficulty":"easy","hint":"Aamir Khan as an alien questioning godmen — \"wrong number!\"","submittedBy":"FilmiGuess Team","crop":{"top":6,"right":60,"bottom":94}},
  {"id":"q82","imageUrl":"https://upload.wikimedia.org/wikipedia/en/d/dd/Bajrangi_Bhaijaan_Poster.jpg","answer":"Bajrangi Bhaijaan","aliases":["bajrangi"],"category":"hindi_movie","difficulty":"easy","hint":"Salman takes a lost Pakistani girl home — \"Mauli kya?\"","submittedBy":"FilmiGuess Team","crop":{"bottom":60}},
  {"id":"q83","imageUrl":"https://upload.wikimedia.org/wikipedia/en/0/07/Gully_Boy_poster.jpg","answer":"Gully Boy","aliases":["gullyboy"],"category":"hindi_movie","difficulty":"medium","hint":"Ranveer as a Dharavi rapper — \"Apna time aayega!\"","submittedBy":"FilmiGuess Team","crop":{"top":8,"bottom":60}},
  {"id":"q84","imageUrl":"https://upload.wikimedia.org/wikipedia/en/4/45/QueenMoviePoster7thMarch.jpg","answer":"Queen","aliases":["queen movie"],"category":"hindi_movie","difficulty":"medium","hint":"Kangana’s solo honeymoon to Paris after a broken wedding","submittedBy":"FilmiGuess Team","crop":{"top":20,"bottom":88}},
  {"id":"q85","imageUrl":"https://upload.wikimedia.org/wikipedia/en/2/2e/Barfi%21_poster.jpg","answer":"Barfi!","aliases":["barfi","barfee"],"category":"hindi_movie","difficulty":"medium","hint":"Ranbir as a mute charmer in Darjeeling","submittedBy":"FilmiGuess Team","crop":{"top":26,"bottom":92}},
  {"id":"q86","imageUrl":"https://upload.wikimedia.org/wikipedia/en/6/68/Rockstar-Movie-Poster.jpg","answer":"Rockstar","aliases":["rockstar movie"],"category":"hindi_movie","difficulty":"medium","hint":"Ranbir as Jordan — \"Sadda Haq\" and a broken heart","submittedBy":"FilmiGuess Team","crop":{"top":21,"bottom":80}},
  {"id":"q87","imageUrl":"https://upload.wikimedia.org/wikipedia/en/1/15/Yeh_jawani_hai_deewani.jpg","answer":"Yeh Jawaani Hai Deewani","aliases":["yjhd","yeh jawani hai deewani"],"category":"hindi_movie","difficulty":"easy","hint":"Bunny and Naina’s trekking trip — \"Badtameez Dil\"","submittedBy":"FilmiGuess Team","crop":{"top":31,"bottom":84}},
  {"id":"q88","imageUrl":"https://upload.wikimedia.org/wikipedia/en/6/6f/War_official_poster.jpg","answer":"War","aliases":["war movie"],"category":"hindi_movie","difficulty":"medium","hint":"Hrithik vs Tiger — spy action and that dance-off","submittedBy":"FilmiGuess Team","crop":{"bottom":66}},
  {"id":"q89","imageUrl":"https://upload.wikimedia.org/wikipedia/en/c/c3/Pathaan_film_poster.jpg","answer":"Pathaan","aliases":["pathan"],"category":"hindi_movie","difficulty":"easy","hint":"SRK’s 2023 comeback — \"Jhoome Jo Pathaan\"","submittedBy":"FilmiGuess Team","crop":{"top":4,"bottom":74}},
  {"id":"q90","imageUrl":"https://upload.wikimedia.org/wikipedia/en/3/39/Jawan_film_poster.jpg","answer":"Jawan","aliases":["jawaan"],"category":"hindi_movie","difficulty":"easy","hint":"Bald SRK with a vigilante army of women — \"Bete ko haath...\"","submittedBy":"FilmiGuess Team","crop":{"right":38,"top":6}},
  {"id":"q91","imageUrl":"https://upload.wikimedia.org/wikipedia/en/9/90/Animal_%282023_film%29_poster.jpg","answer":"Animal","aliases":["animal movie"],"category":"hindi_movie","difficulty":"easy","hint":"Ranbir’s violent father-obsession saga by Sandeep Reddy Vanga","submittedBy":"FilmiGuess Team","crop":{"top":5,"bottom":53}},
  {"id":"q92","imageUrl":"https://upload.wikimedia.org/wikipedia/en/7/73/Padmaavat_poster.jpg","answer":"Padmaavat","aliases":["padmavat","padmavati"],"category":"hindi_movie","difficulty":"medium","hint":"Bhansali epic — Deepika as the Rajput queen, Ranveer as Khilji","submittedBy":"FilmiGuess Team","crop":{"top":17,"bottom":86}},
  {"id":"q93","imageUrl":"https://upload.wikimedia.org/wikipedia/en/c/c0/Bajirao_Mastani_poster.jpg","answer":"Bajirao Mastani","aliases":["bajirao"],"category":"hindi_movie","difficulty":"medium","hint":"Bhansali’s warrior-romance — \"Malhari\" celebration","submittedBy":"FilmiGuess Team","crop":{"top":4,"bottom":54}},
  {"id":"q94","imageUrl":"https://upload.wikimedia.org/wikipedia/en/1/1f/Sultan_film_poster.jpg","answer":"Sultan","aliases":["sultan movie"],"category":"hindi_movie","difficulty":"medium","hint":"Salman as a Haryanvi wrestler making a comeback","submittedBy":"FilmiGuess Team","crop":{"top":16,"bottom":86}},
  {"id":"q95","imageUrl":"https://upload.wikimedia.org/wikipedia/en/4/47/Andhadhun_poster.jpg","answer":"Andhadhun","aliases":["andhadun","blind pianist"],"category":"hindi_movie","difficulty":"hard","hint":"A \"blind\" pianist sees too much — Sriram Raghavan thriller","submittedBy":"FilmiGuess Team","crop":{"top":4,"bottom":70}},
  {"id":"q96","imageUrl":"https://upload.wikimedia.org/wikipedia/en/8/8a/Drishyam_2015_film.jpg","answer":"Drishyam","aliases":["drishyam movie"],"category":"hindi_movie","difficulty":"medium","hint":"Ajay Devgn’s family alibi — \"2nd October ko...\"","submittedBy":"FilmiGuess Team","crop":{"top":4,"bottom":35}},
  {"id":"q97","imageUrl":"https://upload.wikimedia.org/wikipedia/en/4/4f/Stree_-_2018_Movie_Poster.jpg","answer":"Stree","aliases":["stree movie"],"category":"hindi_movie","difficulty":"medium","hint":"\"O Stree, kal aana\" — horror-comedy in Chanderi","submittedBy":"FilmiGuess Team","crop":{"top":10,"bottom":74}},
  {"id":"q98","imageUrl":"https://upload.wikimedia.org/wikipedia/en/d/dc/Kabir_Singh.jpg","answer":"Kabir Singh","aliases":["kabir singh movie"],"category":"hindi_movie","difficulty":"easy","hint":"Shahid as a self-destructive surgeon in love","submittedBy":"FilmiGuess Team","crop":{"top":4,"bottom":60}},
  {"id":"q99","imageUrl":"https://upload.wikimedia.org/wikipedia/en/4/41/Om_Shanti_Om.jpg","answer":"Om Shanti Om","aliases":["oso"],"category":"hindi_movie","difficulty":"easy","hint":"SRK’s reincarnation masala — \"Ek chutki sindoor\"","submittedBy":"FilmiGuess Team","crop":{"top":3,"bottom":54}},
  {"id":"q100","imageUrl":"https://upload.wikimedia.org/wikipedia/en/9/9a/Devdas_%282002_Hindi_film%29.jpg","answer":"Devdas","aliases":["devdas 2002"],"category":"hindi_movie","difficulty":"medium","hint":"SRK drowning in heartbreak between Paro and Chandramukhi","submittedBy":"FilmiGuess Team","crop":{"top":4,"bottom":58}},
  {"id":"q101","imageUrl":"https://upload.wikimedia.org/wikipedia/en/a/aa/Kal_Ho_Naa_Ho_poster.jpg","answer":"Kal Ho Naa Ho","aliases":["khnh","kal ho na ho"],"category":"hindi_movie","difficulty":"easy","hint":"SRK’s Aman fixes everyone’s life but his own — New York tears","submittedBy":"FilmiGuess Team","crop":{"bottom":70}},
  {"id":"q102","imageUrl":"https://upload.wikimedia.org/wikipedia/en/0/08/Rang_De_Basanti_poster.jpg","answer":"Rang De Basanti","aliases":["rdb"],"category":"hindi_movie","difficulty":"medium","hint":"College kids reenact freedom fighters — Aamir’s 2006 wake-up call","submittedBy":"FilmiGuess Team","crop":{"bottom":40}},
  {"id":"q103","imageUrl":"https://upload.wikimedia.org/wikipedia/en/b/b4/Taare_Zameen_Par_Like_Stars_on_Earth_poster.png","answer":"Taare Zameen Par","aliases":["tzp","taare zamin par"],"category":"hindi_movie","difficulty":"easy","hint":"A dyslexic kid and his art teacher — every child is special","submittedBy":"FilmiGuess Team","crop":{"top":44,"bottom":92}},
  {"id":"q104","imageUrl":"https://upload.wikimedia.org/wikipedia/en/0/0c/Chak_De%21_India.jpg","answer":"Chak De! India","aliases":["chak de","chak de india"],"category":"hindi_movie","difficulty":"easy","hint":"SRK coaches the women’s hockey team — \"Sattar minute\"","submittedBy":"FilmiGuess Team","crop":{"top":2,"bottom":76}},
  {"id":"q105","imageUrl":"https://upload.wikimedia.org/wikipedia/en/8/85/Swades_poster.jpg","answer":"Swades","aliases":["swadesh"],"category":"hindi_movie","difficulty":"medium","hint":"NASA scientist returns to light up a village — \"Yeh jo des hai tera\"","submittedBy":"FilmiGuess Team","crop":{"top":26,"bottom":94}},
  {"id":"q106","imageUrl":"https://upload.wikimedia.org/wikipedia/en/1/1b/Chennai_Express.jpg","answer":"Chennai Express","aliases":["chennai express movie"],"category":"hindi_movie","difficulty":"easy","hint":"SRK’s accidental train ride south — \"Lungi Dance\"","submittedBy":"FilmiGuess Team","crop":{"top":4,"bottom":60}},
  {"id":"q107","imageUrl":"https://upload.wikimedia.org/wikipedia/en/4/41/Tumbbad_poster.jpg","answer":"Tumbbad","aliases":["tumbad"],"category":"hindi_movie","difficulty":"hard","hint":"Rain-soaked mythological horror about greed and Hastar","submittedBy":"FilmiGuess Team","crop":{"top":18,"bottom":92}},
  {"id":"q108","imageUrl":"https://upload.wikimedia.org/wikipedia/en/2/20/Mother_India_poster.jpg","answer":"Mother India","aliases":["mother india movie"],"category":"classic_movie","difficulty":"medium","hint":"1957 epic — Nargis as the iron-willed village mother","submittedBy":"FilmiGuess Team","crop":{"top":32,"bottom":80}},
  {"id":"q109","imageUrl":"https://upload.wikimedia.org/wikipedia/en/4/43/Guide_1965_film_poster.jpg","answer":"Guide","aliases":["the guide"],"category":"classic_movie","difficulty":"hard","hint":"Dev Anand and Waheeda Rehman — 1965 Vijay Anand classic","submittedBy":"FilmiGuess Team","crop":{"top":5,"bottom":60}},
  {"id":"q110","imageUrl":"https://upload.wikimedia.org/wikipedia/en/c/c9/Anand_film.jpg","answer":"Anand","aliases":["anand movie"],"category":"classic_movie","difficulty":"medium","hint":"Rajesh Khanna’s dying optimist — \"Babumoshai!\"","submittedBy":"FilmiGuess Team","crop":{"top":28,"bottom":92}},
  {"id":"q111","imageUrl":"https://upload.wikimedia.org/wikipedia/en/0/0e/Don_1978_poster.jpg","answer":"Don","aliases":["don 1978"],"category":"classic_movie","difficulty":"medium","hint":"Amitabh’s double role — \"Don ko pakadna mushkil hi nahin...\"","submittedBy":"FilmiGuess Team","crop":{"top":26,"bottom":60}},
  {"id":"q112","imageUrl":"https://upload.wikimedia.org/wikipedia/en/d/d7/Mr._India_%281987_film%29_poster.jpg","answer":"Mr. India","aliases":["mr india","mister india"],"category":"classic_movie","difficulty":"easy","hint":"Invisible Anil Kapoor vs \"Mogambo khush hua!\"","submittedBy":"FilmiGuess Team","crop":{"top":3,"bottom":56}},
  {"id":"q113","imageUrl":"https://upload.wikimedia.org/wikipedia/en/0/09/Amar_Akbar_Anthony_1977_film_poster.jpg","answer":"Amar Akbar Anthony","aliases":["amar akbar anthony movie"],"category":"classic_movie","difficulty":"medium","hint":"Three separated brothers, three religions — Manmohan Desai masala","submittedBy":"FilmiGuess Team","crop":{"left":22,"top":3,"bottom":64}},
  {"id":"q114","imageUrl":"https://upload.wikimedia.org/wikipedia/en/8/87/Hum_Aapke_Hain_Koun.._poster.jpg","answer":"Hum Aapke Hain Koun..!","aliases":["hahk","hum aapke hain kaun"],"category":"classic_movie","difficulty":"easy","hint":"Salman-Madhuri wedding extravaganza of 1994","submittedBy":"FilmiGuess Team","crop":{"top":13,"bottom":62}},
  {"id":"q115","imageUrl":"https://upload.wikimedia.org/wikipedia/en/8/85/Baazigar_1993.jpg","answer":"Baazigar","aliases":["bazigar"],"category":"classic_movie","difficulty":"medium","hint":"SRK’s anti-hero breakthrough — \"Haar ke jeetne wale ko...\"","submittedBy":"FilmiGuess Team","crop":{"top":9,"bottom":72}},
  {"id":"q116","imageUrl":"https://upload.wikimedia.org/wikipedia/en/9/96/Maine_Pyar_Kiya.jpg","answer":"Maine Pyar Kiya","aliases":["mpk"],"category":"classic_movie","difficulty":"medium","hint":"Salman’s 1989 debut romance — \"Dosti ka ek usool hai\"","submittedBy":"FilmiGuess Team","crop":{"top":4,"bottom":50}},
  {"id":"q117","imageUrl":"https://upload.wikimedia.org/wikipedia/en/1/1d/Disco_Dancer.jpg","answer":"Disco Dancer","aliases":["disco dancer movie"],"category":"classic_movie","difficulty":"hard","hint":"Mithun’s \"Jimmy Jimmy Aaja\" — 1982 disco fever","submittedBy":"FilmiGuess Team","crop":{"top":28,"bottom":60}},
];
